### ISSUE TITLE
Dev will not be the main branch

### ISSUE THREAD

**Issue by danielet** [HPIMS/dm-consents#22]
@fix92 one day will need to move away from dev as "main" branch

**Comment by klandell** [comment]
Main should be main... We can set up branch protection rules so that updates to main require a pull request to get around the concern that something would be committed to main by mistake.

**Comment by fix92** [comment]
I would also suggest to set all the projects (dm-studies, dm-consents, dm-redeem-code-api, digime-fhir-store, digi-me-deployment (or others) to configure them that a pull request must be created (for master/main at least. For sandbox, dev it's optional I guess). The approvals can still be optional or one can force merge the PR if no-ones around to approve

**Comment by danielet** [comment]
@fix92 ok I liked it
